# Generated by Django 5.1.2 on 2024-10-26 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emastrategy_predictedpricemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedpricemodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='predictedpricemodel',
            name='predicted_price',
            field=models.FloatField(default=0.0),
        ),
    ]
